// apps/demos/Demos/HtmlEditor/MarkdownSupport/Vue/App.vue
<template>
  <div class="widget-container">
    <DxHtmlEditor
      v-model:value="valueContent"
      :height="300"
      :converter="converter"
    >
      <DxToolbar>
        <DxItem name="undo"/>
        <DxItem name="redo"/>
        <DxItem name="separator"/>
        <DxItem name="bold"/>
        <DxItem name="italic"/>
        <DxItem name="separator"/>
        <DxItem
          name="header"
          :accepted-values="headerValues"
          :options="headerOptions"
        />
      </DxToolbar>
    </DxHtmlEditor>

    <div class="options">
      <div class="value-title">
        Contents of the value option
      </div>
      <div
        class="value-content"
        tabindex="0"
      >
        {{ valueContent }}
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import {
  DxHtmlEditor,
  DxToolbar,
  DxItem,
} from 'devextreme-vue/html-editor';
import { markup } from './data.ts';

const valueContent = ref(markup);
const headerValues = [false, 1, 2, 3, 4, 5];
const headerOptions = { inputAttr: { 'aria-label': 'Font family' } };
const converter = {
  toHtml(value) {
    // @ts-expect-error
    const result = unified()
      // @ts-expect-error
      .use(remarkParse)
      // @ts-expect-error
      // eslint-disable-next-line spellcheck/spell-checker
      .use(remarkRehype)
      // @ts-expect-error
      // eslint-disable-next-line spellcheck/spell-checker
      .use(rehypeStringify)
      .processSync(value)
      .toString();

    return result;
  },
  fromHtml(value) {
    // @ts-expect-error
    const result = unified()
      // @ts-expect-error
      // eslint-disable-next-line spellcheck/spell-checker
      .use(rehypeParse)
      // eslint-disable-next-line spellcheck/spell-checker
      // @ts-expect-error
      .use(rehypeRemark)
      // @ts-expect-error
      .use(remarkStringify)
      .processSync(value)
      .toString();

    return result;
  },
};
</script>
<style>
.value-title {
  font-size: 18px;
  font-weight: 500;
}

.value-content {
  margin-top: 20px;
  overflow: auto;
  height: 110px;
  width: 100%;
  white-space: pre-wrap;
}

.options {
  margin-top: 20px;
  padding: 20px;
  background-color: rgba(191, 191, 191, 0.15);
  box-sizing: border-box;
  width: 100%;
}
</style>

// apps/demos/Demos/HtmlEditor/MarkdownSupport/React/App.tsx
import React, { useCallback, useState } from 'react';
import HtmlEditor, { Toolbar, Item } from 'devextreme-react/html-editor';
import { markup } from './data.ts';

const headerValues = [false, 1, 2, 3, 4, 5];
const headerOptions = {
  inputAttr: {
    'aria-label': 'Font family',
  },
};
const converter = {
  toHtml(value) {
    // @ts-expect-error
    const result = unified()
      // @ts-expect-error
      .use(remarkParse)
      // @ts-expect-error
      // eslint-disable-next-line spellcheck/spell-checker
      .use(remarkRehype)
      // @ts-expect-error
      // eslint-disable-next-line spellcheck/spell-checker
      .use(rehypeStringify)
      .processSync(value)
      .toString();

    return result;
  },
  fromHtml(value) {
    // @ts-expect-error
    const result = unified()
      // @ts-expect-error
      // eslint-disable-next-line spellcheck/spell-checker
      .use(rehypeParse)
      // eslint-disable-next-line spellcheck/spell-checker
      // @ts-expect-error
      .use(rehypeRemark)
      // @ts-expect-error
      .use(remarkStringify)
      .processSync(value)
      .toString();

    return result;
  },
};

export default function App() {
  const [valueContent, setValueContent] = useState(markup);

  const valueChanged = useCallback((e: { value?: string; }) => {
    setValueContent(e.value);
  }, [setValueContent]);

  return (
    <div className="widget-container">
      <HtmlEditor
        converter={converter}
        height={300}
        defaultValue={valueContent}
        onValueChanged={valueChanged}
      >
        <Toolbar>
          <Item name="undo" />
          <Item name="redo" />
          <Item name="separator" />
          <Item name="bold" />
          <Item name="italic" />
          <Item name="separator" />
          <Item name="header" acceptedValues={headerValues} options={headerOptions} />
        </Toolbar>
      </HtmlEditor>

      <div className="options">
        <div className="value-title">
          Contents of the value option
        </div>
        <div className="value-content" tabIndex={0}>
          {valueContent}
        </div>
      </div>
    </div>
  );
}
